/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_agegenerator_free(a: number): void;
export function __wbg_get_agegenerator_median_age(a: number): number;
export function __wbg_set_agegenerator_median_age(a: number, b: number): void;
export function agegenerator_new(a: number): number;
export function agegenerator_generate_age(a: number): number;
export function __wbg_legacyagegenerator_free(a: number): void;
export function legacyagegenerator_new(a: number): number;
export function legacyagegenerator_generate_age(a: number): number;
export function __wbg_normaldistribution_free(a: number): void;
export function normaldistribution_new(a: number, b: number): number;
export function normaldistribution_pdf(a: number, b: number): number;
export function normaldistribution_cdf(a: number, b: number): number;
export function normaldistribution_quartile(a: number, b: number): number;
export function __wbg_get_legacyagegenerator_median_age(a: number): number;
export function agegenerator_update_median_age(a: number, b: number): void;
export function __wbg_set_legacyagegenerator_median_age(a: number, b: number): void;
export function __wbg_bean_free(a: number): void;
export function bean_new(a: number, b: number): number;
export function bean_get_age(a: number): number;
export function bean_get_factors(a: number): number;
export function bean_dies(a: number, b: number): number;
export function __wbg_get_simulation_settings(a: number): number;
export function __wbg_set_simulation_settings(a: number, b: number): void;
export function simulation_new(a: number): number;
export function __wbg_simulationresult_free(a: number): void;
export function __wbg_get_simulationresult_population(a: number): number;
export function __wbg_set_simulationresult_population(a: number, b: number): void;
export function simulationresult_get_population_curve(a: number, b: number): void;
export function simulationresult_new(a: number, b: number, c: number): number;
export function __wbg_settings_free(a: number): void;
export function __wbg_get_settings_years(a: number): number;
export function __wbg_set_settings_years(a: number, b: number): void;
export function __wbg_get_settings_population(a: number): number;
export function __wbg_set_settings_population(a: number, b: number): void;
export function __wbg_get_settings_max_age(a: number): number;
export function __wbg_set_settings_max_age(a: number, b: number): void;
export function __wbg_get_settings_smokers(a: number): number;
export function __wbg_set_settings_smokers(a: number, b: number): void;
export function __wbg_get_settings_weed_smokers(a: number): number;
export function __wbg_set_settings_weed_smokers(a: number, b: number): void;
export function __wbg_get_settings_vapers(a: number): number;
export function __wbg_set_settings_vapers(a: number, b: number): void;
export function __wbg_get_settings_drinkers(a: number): number;
export function __wbg_set_settings_drinkers(a: number, b: number): void;
export function __wbg_get_settings_hard_drugger(a: number): number;
export function __wbg_set_settings_hard_drugger(a: number, b: number): void;
export function __wbg_get_settings_sugar(a: number): number;
export function __wbg_set_settings_sugar(a: number, b: number): void;
export function __wbg_get_settings_salt(a: number): number;
export function __wbg_set_settings_salt(a: number, b: number): void;
export function __wbg_get_settings_fat(a: number): number;
export function __wbg_set_settings_fat(a: number, b: number): void;
export function __wbg_get_settings_vitamins(a: number): number;
export function __wbg_set_settings_vitamins(a: number, b: number): void;
export function __wbg_get_settings_wealth_factor(a: number): number;
export function __wbg_set_settings_wealth_factor(a: number, b: number): void;
export function settings_new(): number;
export function simulationresult_get_population(a: number): number;
export function settings_set_population(a: number, b: number): void;
export function settings_set_max_age(a: number, b: number): void;
export function settings_set_smokers(a: number, b: number): void;
export function settings_set_weed_smokers(a: number, b: number): void;
export function settings_set_vapers(a: number, b: number): void;
export function settings_set_drinkers(a: number, b: number): void;
export function settings_set_sugar(a: number, b: number): void;
export function settings_set_salt(a: number, b: number): void;
export function settings_set_fat(a: number, b: number): void;
export function settings_set_vitamins(a: number, b: number): void;
export function settings_set_wealth_factor(a: number, b: number): void;
export function settings_set_hard_drugger(a: number, b: number): void;
export function settings_set_years(a: number, b: number): void;
export function __wbg_simulation_free(a: number): void;
export function __wbg_fat_free(a: number): void;
export function __wbg_get_fat_value(a: number): number;
export function __wbg_set_fat_value(a: number, b: number): void;
export function __wbg_factors_free(a: number): void;
export function __wbg_get_factors_alcoholism(a: number): number;
export function __wbg_set_factors_alcoholism(a: number, b: number): void;
export function __wbg_get_factors_binge_drinker(a: number): number;
export function __wbg_set_factors_binge_drinker(a: number, b: number): void;
export function __wbg_get_factors_smokes_weed(a: number): number;
export function __wbg_set_factors_smokes_weed(a: number, b: number): void;
export function __wbg_get_factors_smokes_cigarettes(a: number): number;
export function __wbg_set_factors_smokes_cigarettes(a: number, b: number): void;
export function __wbg_get_factors_smokes_vape(a: number): number;
export function __wbg_set_factors_smokes_vape(a: number, b: number): void;
export function __wbg_get_factors_consumes_hard_drugs(a: number): number;
export function __wbg_set_factors_consumes_hard_drugs(a: number, b: number): void;
export function __wbg_get_factors_sugar(a: number): number;
export function __wbg_set_factors_sugar(a: number, b: number): void;
export function __wbg_get_factors_salt(a: number): number;
export function __wbg_set_factors_salt(a: number, b: number): void;
export function __wbg_get_factors_fat(a: number): number;
export function __wbg_set_factors_fat(a: number, b: number): void;
export function __wbg_get_factors_vitamins(a: number): number;
export function __wbg_set_factors_vitamins(a: number, b: number): void;
export function __wbg_get_factors_wealth(a: number): number;
export function __wbg_set_factors_wealth(a: number, b: number): void;
export function factors_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number): number;
export function __wbg_get_sugar_value(a: number): number;
export function __wbg_get_salt_value(a: number): number;
export function __wbg_get_vitamins_value(a: number): number;
export function __wbg_get_wealth_value(a: number): number;
export function __wbg_set_sugar_value(a: number, b: number): void;
export function __wbg_set_salt_value(a: number, b: number): void;
export function __wbg_set_vitamins_value(a: number, b: number): void;
export function __wbg_set_wealth_value(a: number, b: number): void;
export function __wbg_sugar_free(a: number): void;
export function __wbg_salt_free(a: number): void;
export function __wbg_vitamins_free(a: number): void;
export function __wbg_wealth_free(a: number): void;
export function simulation_long(a: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_exn_store(a: number): void;
